version: "3.9"

services:
  nginx_reverse_proxy:
    image: custom_nginx
    build:
      context: ./nginx-proxy
    env_file:
      - .env
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    networks:
      - my_network

  app_service:
    image: app_service
    build:
      context: ./app-service
    env_file:
      - .env
    volumes:
      - ./app-service:/app-service
      - /app-service/node_modules
    depends_on:
      - redis
    networks:
      - my_network

  redis:
    image: redis:7.2-rc-alpine
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: ["redis-server", "--bind", "${REDIS_HOST}", "--port", "${REDIS_PORT}"]
    env_file:
      - .env
    networks:
      - my_network

  worker:
    image: worker
    build:
      context: ./worker
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./worker:/worker
    networks:
      - my_network

  client:
    image: client
    build:
      context: ./client
    env_file:
      - .env
    volumes:
      - ./client:/client
      - /client/node_modules
    tty: true
    stdin_open: true
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"

networks:
  my_network:
