version: "3.9"

services:
  nginx_reverse_proxy:
    image: custom_nginx
    build:
      context: ./nginx-proxy
    env_file:
      - .env
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    networks:
      - my_network

  app_service:
    image: app_service
    build:
      context: ./app-service
    volumes:
      - ./app-service:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - my_network

  redis:
    image: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: ["redis-server", "--bind", "${REDIS_HOST}", "--port", "${REDIS_PORT}"]
    env_file:
      - .env
    networks:
      - my_network

  worker:
    image: worker
    build:
      context: ./worker
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./worker:/app
    networks:
      - my_network

  client:
    image: client
    build:
      context: ./client
    env_file:
      - .env
    ports:
        - "${CLIENT_PORT}:${CLIENT_PORT}"
    volumes:
      - ./client:/app
      - /app/node_modules

networks:
  my_network:
